import { createHash } from 'node:crypto';
import { deflateRawSync } from 'node:zlib';

/**
 * A minimal ZIP writer (phase 7.2).
 *
 * Hand-written rather than pulled from npm, and the reason is proportion: the
 * export archive contains a handful of JSON documents and a README, all of them
 * small, all of them generated by us. That needs the *stored* and *deflate*
 * halves of APPNOTE 6.3.3 and nothing else — no streaming, no encryption, no
 * ZIP64, no directory entries. A dependency for that is a supply-chain surface
 * around a file format that has not changed since 1993.
 *
 * What it does implement carefully is the part that goes wrong: CRC-32 over the
 * *uncompressed* bytes, sizes in both the local header and the central
 * directory, and a correct end-of-central-directory record. A ZIP that Windows
 * Explorer opens and `unzip` rejects is the usual outcome of getting one of
 * those wrong, and a customer's data-access request answered with a corrupt
 * archive is a refusal with extra steps.
 *
 * Non-goals, stated so nobody extends this into a general-purpose library:
 * files over 4 GB (ZIP64), directories, timestamps beyond a fixed epoch, and
 * anything with a non-ASCII filename. The exporter controls every name it
 * writes, and `assertWritableName` enforces that rather than trusting it.
 */

export interface ZipEntry {
  readonly name: string;
  readonly bytes: Buffer;
}

export interface ZipResult {
  readonly bytes: Buffer;
  readonly sha256: string;
}

const SIG_LOCAL = 0x04034b50;
const SIG_CENTRAL = 0x02014b50;
const SIG_END = 0x06054b50;
/** Deflate. `0` (stored) is used when deflating would make the entry bigger. */
const METHOD_DEFLATE = 8;
const METHOD_STORED = 0;
/** 1980-01-01 00:00, the DOS epoch. A fixed time makes archives reproducible. */
const DOS_TIME = 0;
const DOS_DATE = 0x0021;

export function writeZip(entries: readonly ZipEntry[]): ZipResult {
  const locals: Buffer[] = [];
  const centrals: Buffer[] = [];
  let offset = 0;

  for (const entry of entries) {
    assertWritableName(entry.name);
    const name = Buffer.from(entry.name, 'ascii');
    const crc = crc32(entry.bytes);

    const deflated = deflateRawSync(entry.bytes);
    // Deflate expands incompressible input. A README of 900 bytes is not that,
    // but a tiny JSON document can be, and storing it is both smaller and
    // faster to read back.
    const useDeflate = deflated.length < entry.bytes.length;
    const payload = useDeflate ? deflated : entry.bytes;
    const method = useDeflate ? METHOD_DEFLATE : METHOD_STORED;

    const local = Buffer.alloc(30);
    local.writeUInt32LE(SIG_LOCAL, 0);
    local.writeUInt16LE(20, 4); // version needed: 2.0
    local.writeUInt16LE(0, 6); // flags
    local.writeUInt16LE(method, 8);
    local.writeUInt16LE(DOS_TIME, 10);
    local.writeUInt16LE(DOS_DATE, 12);
    local.writeUInt32LE(crc, 14);
    local.writeUInt32LE(payload.length, 18);
    local.writeUInt32LE(entry.bytes.length, 22);
    local.writeUInt16LE(name.length, 26);
    local.writeUInt16LE(0, 28); // extra field length

    locals.push(local, name, payload);

    const central = Buffer.alloc(46);
    central.writeUInt32LE(SIG_CENTRAL, 0);
    central.writeUInt16LE(20, 4); // version made by
    central.writeUInt16LE(20, 6); // version needed
    central.writeUInt16LE(0, 8);
    central.writeUInt16LE(method, 10);
    central.writeUInt16LE(DOS_TIME, 12);
    central.writeUInt16LE(DOS_DATE, 14);
    central.writeUInt32LE(crc, 16);
    central.writeUInt32LE(payload.length, 20);
    central.writeUInt32LE(entry.bytes.length, 24);
    central.writeUInt16LE(name.length, 28);
    central.writeUInt16LE(0, 30); // extra
    central.writeUInt16LE(0, 32); // comment
    central.writeUInt16LE(0, 34); // disk number
    central.writeUInt16LE(0, 36); // internal attrs
    central.writeUInt32LE(0, 38); // external attrs
    central.writeUInt32LE(offset, 42);

    centrals.push(central, name);
    offset += local.length + name.length + payload.length;
  }

  const centralBytes = Buffer.concat(centrals);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(SIG_END, 0);
  end.writeUInt16LE(0, 4); // this disk
  end.writeUInt16LE(0, 6); // disk with central directory
  end.writeUInt16LE(entries.length, 8);
  end.writeUInt16LE(entries.length, 10);
  end.writeUInt32LE(centralBytes.length, 12);
  end.writeUInt32LE(offset, 16);
  end.writeUInt16LE(0, 20); // comment length

  const bytes = Buffer.concat([...locals, centralBytes, end]);
  return { bytes, sha256: createHash('sha256').update(bytes).digest('hex') };
}

/**
 * Names are ours, and this proves it.
 *
 * A path separator or a `..` in an archive entry is the Zip-Slip class of bug:
 * whatever the customer extracts with will happily write outside the target
 * directory. Every name in this archive is a constant in `archiveEntries`, so
 * this can never fire — which is exactly when a check is cheap and worth having,
 * because the day somebody adds a name derived from a job-card code is the day
 * it matters.
 */
function assertWritableName(name: string): void {
  if (name === '' || name.length > 200) {
    throw new Error(`Archive entry name is not usable: "${name}"`);
  }
  if (!/^[A-Za-z0-9._-]+$/.test(name)) {
    throw new Error(
      `Archive entry name "${name}" must be plain ASCII with no path separators`,
    );
  }
}

/** Table-driven CRC-32 (IEEE 802.3), computed once at module load. */
const CRC_TABLE = ((): Uint32Array => {
  const table = new Uint32Array(256);
  for (let index = 0; index < 256; index += 1) {
    let value = index;
    for (let bit = 0; bit < 8; bit += 1) {
      value = (value & 1) === 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
    }
    table[index] = value >>> 0;
  }
  return table;
})();

export function crc32(bytes: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc = (CRC_TABLE[(crc ^ byte) & 0xff] as number) ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
